[build]
  # أمر البناء (build command) المستخدم لتجميع المشروع
  command = "npm run build"
  
  # المجلد الذي سيتم نشره بعد البناء (publish directory)
  publish = "build"

  # إذا كان مشروعك في مجلد فرعي، أضف المسار هنا (Base directory)
  # base = "path/to/your/subdirectory"

[build.environment]
  # إذا كنت بحاجة إلى متغيرات بيئة خاصة بالبناء، يمكنك إضافتها هنا
  NODE_ENV = "production"

# إعدادات اختيارية للوظائف (functions) إذا كنت تستخدم وظائف Netlify
[functions]
  directory = "netlify/functions"

# يمكنك إضافة إعدادات لإعادة التوجيهات (redirects) هنا إذا لزم الأمر
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
